/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export declare namespace ERC2771Forwarder {
  export type ForwardRequestDataStruct = {
    from: PromiseOrValue<string>;
    to: PromiseOrValue<string>;
    value: PromiseOrValue<BigNumberish>;
    gas: PromiseOrValue<BigNumberish>;
    deadline: PromiseOrValue<BigNumberish>;
    data: PromiseOrValue<BytesLike>;
    signature: PromiseOrValue<BytesLike>;
  };

  export type ForwardRequestDataStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber,
    number,
    string,
    string
  ] & {
    from: string;
    to: string;
    value: BigNumber;
    gas: BigNumber;
    deadline: number;
    data: string;
    signature: string;
  };
}

export interface ERC2771ForwarderInterface extends utils.Interface {
  functions: {
    "eip712Domain()": FunctionFragment;
    "execute((address,address,uint256,uint256,uint48,bytes,bytes))": FunctionFragment;
    "executeBatch((address,address,uint256,uint256,uint48,bytes,bytes)[],address)": FunctionFragment;
    "nonces(address)": FunctionFragment;
    "verify((address,address,uint256,uint256,uint48,bytes,bytes))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "eip712Domain"
      | "execute"
      | "executeBatch"
      | "nonces"
      | "verify"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [ERC2771Forwarder.ForwardRequestDataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBatch",
    values: [
      ERC2771Forwarder.ForwardRequestDataStruct[],
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "nonces",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [ERC2771Forwarder.ForwardRequestDataStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {
    "EIP712DomainChanged()": EventFragment;
    "ExecutedForwardRequest(address,uint256,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "EIP712DomainChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExecutedForwardRequest"): EventFragment;
}

export interface EIP712DomainChangedEventObject {}
export type EIP712DomainChangedEvent = TypedEvent<
  [],
  EIP712DomainChangedEventObject
>;

export type EIP712DomainChangedEventFilter =
  TypedEventFilter<EIP712DomainChangedEvent>;

export interface ExecutedForwardRequestEventObject {
  signer: string;
  nonce: BigNumber;
  success: boolean;
}
export type ExecutedForwardRequestEvent = TypedEvent<
  [string, BigNumber, boolean],
  ExecutedForwardRequestEventObject
>;

export type ExecutedForwardRequestEventFilter =
  TypedEventFilter<ExecutedForwardRequestEvent>;

export interface ERC2771Forwarder extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ERC2771ForwarderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    eip712Domain(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber, string, string, BigNumber[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: BigNumber;
        verifyingContract: string;
        salt: string;
        extensions: BigNumber[];
      }
    >;

    execute(
      request: ERC2771Forwarder.ForwardRequestDataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    executeBatch(
      requests: ERC2771Forwarder.ForwardRequestDataStruct[],
      refundReceiver: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    nonces(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    verify(
      request: ERC2771Forwarder.ForwardRequestDataStruct,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  eip712Domain(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, BigNumber, string, string, BigNumber[]] & {
      fields: string;
      name: string;
      version: string;
      chainId: BigNumber;
      verifyingContract: string;
      salt: string;
      extensions: BigNumber[];
    }
  >;

  execute(
    request: ERC2771Forwarder.ForwardRequestDataStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  executeBatch(
    requests: ERC2771Forwarder.ForwardRequestDataStruct[],
    refundReceiver: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  nonces(
    owner: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  verify(
    request: ERC2771Forwarder.ForwardRequestDataStruct,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    eip712Domain(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber, string, string, BigNumber[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: BigNumber;
        verifyingContract: string;
        salt: string;
        extensions: BigNumber[];
      }
    >;

    execute(
      request: ERC2771Forwarder.ForwardRequestDataStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    executeBatch(
      requests: ERC2771Forwarder.ForwardRequestDataStruct[],
      refundReceiver: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    nonces(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verify(
      request: ERC2771Forwarder.ForwardRequestDataStruct,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "EIP712DomainChanged()"(): EIP712DomainChangedEventFilter;
    EIP712DomainChanged(): EIP712DomainChangedEventFilter;

    "ExecutedForwardRequest(address,uint256,bool)"(
      signer?: PromiseOrValue<string> | null,
      nonce?: null,
      success?: null
    ): ExecutedForwardRequestEventFilter;
    ExecutedForwardRequest(
      signer?: PromiseOrValue<string> | null,
      nonce?: null,
      success?: null
    ): ExecutedForwardRequestEventFilter;
  };

  estimateGas: {
    eip712Domain(overrides?: CallOverrides): Promise<BigNumber>;

    execute(
      request: ERC2771Forwarder.ForwardRequestDataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    executeBatch(
      requests: ERC2771Forwarder.ForwardRequestDataStruct[],
      refundReceiver: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    nonces(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verify(
      request: ERC2771Forwarder.ForwardRequestDataStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    eip712Domain(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    execute(
      request: ERC2771Forwarder.ForwardRequestDataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    executeBatch(
      requests: ERC2771Forwarder.ForwardRequestDataStruct[],
      refundReceiver: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    nonces(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verify(
      request: ERC2771Forwarder.ForwardRequestDataStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
